export interface Problem {
  id: number;
  title: string;
  completed: boolean;
  acceptance: number;
  difficulty: "Easy" | "Medium" | "Hard";
}

export const problems: Problem[] = [
  {
    id: 1,
    title: "Minimum Array End",
    completed: true,
    acceptance: 55.4,
    difficulty: "Medium",
  },
  {
    id: 2,
    title: "Two Sum",
    completed: true,
    acceptance: 54.2,
    difficulty: "Easy",
  },
  {
    id: 3,
    title: "Add Two Numbers",
    completed: true,
    acceptance: 44.5,
    difficulty: "Medium",
  },
  {
    id: 4,
    title: "Reverse Linked List",
    completed: true,
    acceptance: 62.8,
    difficulty: "Easy",
  },
  {
    id: 5,
    title: "Longest Substring Without Repeating Characters",
    completed: true,
    acceptance: 43.7,
    difficulty: "Hard",
  },
  {
    id: 6,
    title: "Palindrome Number",
    completed: true,
    acceptance: 59.1,
    difficulty: "Easy",
  },
  {
    id: 7,
    title: "Climbing Stairs",
    completed: true,
    acceptance: 72.3,
    difficulty: "Easy",
  },
  {
    id: 8,
    title: "Valid Parentheses",
    completed: true,
    acceptance: 60.4,
    difficulty: "Easy",
  },
  {
    id: 9,
    title: "Merge Two Sorted Lists",
    completed: true,
    acceptance: 67.9,
    difficulty: "Easy",
  },
  {
    id: 10,
    title: "Maximum Subarray",
    completed: true,
    acceptance: 55.9,
    difficulty: "Medium",
  },
  {
    id: 11,
    title: "Best Time to Buy and Sell Stock",
    completed: true,
    acceptance: 57.4,
    difficulty: "Easy",
  },
  {
    id: 12,
    title: "Same Tree",
    completed: true,
    acceptance: 72.1,
    difficulty: "Easy",
  },
  {
    id: 13,
    title: "Symmetric Tree",
    completed: true,
    acceptance: 68.3,
    difficulty: "Medium",
  },
  {
    id: 14,
    title: "Path Sum",
    completed: true,
    acceptance: 62.9,
    difficulty: "Easy",
  },
  {
    id: 15,
    title: "Intersection of Two Linked Lists",
    completed: true,
    acceptance: 74.5,
    difficulty: "Easy",
  },
  {
    id: 16,
    title: "Merge Intervals",
    completed: true,
    acceptance: 56.1,
    difficulty: "Medium",
  },
  {
    id: 17,
    title: "Contains Duplicate",
    completed: true,
    acceptance: 72.2,
    difficulty: "Easy",
  },
  {
    id: 18,
    title: "Sum of Two Integers",
    completed: true,
    acceptance: 80.1,
    difficulty: "Easy",
  },
  {
    id: 19,
    title: "Roman to Integer",
    completed: true,
    acceptance: 79.3,
    difficulty: "Easy",
  },
  {
    id: 20,
    title: "Longest Common Prefix",
    completed: true,
    acceptance: 56.3,
    difficulty: "Easy",
  },
  {
    id: 21,
    title: "Move Zeroes",
    completed: true,
    acceptance: 66.7,
    difficulty: "Medium",
  },
  {
    id: 22,
    title: "Find the Duplicate Number",
    completed: true,
    acceptance: 75.5,
    difficulty: "Medium",
  },
  {
    id: 23,
    title: "Remove Duplicates from Sorted Array",
    completed: true,
    acceptance: 75.0,
    difficulty: "Easy",
  },
  {
    id: 24,
    title: "Add Binary",
    completed: true,
    acceptance: 67.5,
    difficulty: "Easy",
  },
  {
    id: 25,
    title: "Find Minimum in Rotated Sorted Array",
    completed: true,
    acceptance: 50.2,
    difficulty: "Medium",
  },
  {
    id: 26,
    title: "Binary Search",
    completed: true,
    acceptance: 77.9,
    difficulty: "Medium",
  },
  {
    id: 27,
    title: "Count Primes",
    completed: true,
    acceptance: 70.2,
    difficulty: "Medium",
  },
  {
    id: 28,
    title: "Sqrt(x)",
    completed: true,
    acceptance: 74.4,
    difficulty: "Easy",
  },
  {
    id: 29,
    title: "Product of Array Except Self",
    completed: true,
    acceptance: 54.1,
    difficulty: "Medium",
  },
  {
    id: 30,
    title: "Majority Element",
    completed: true,
    acceptance: 72.8,
    difficulty: "Easy",
  },
  {
    id: 31,
    title: "House Robber",
    completed: true,
    acceptance: 61.5,
    difficulty: "Medium",
  },
  {
    id: 32,
    title: "Maximum Product Subarray",
    completed: true,
    acceptance: 50.7,
    difficulty: "Medium",
  },
  {
    id: 33,
    title: "Valid Anagram",
    completed: true,
    acceptance: 74.1,
    difficulty: "Easy",
  },
  {
    id: 34,
    title: "Single Number",
    completed: true,
    acceptance: 73.0,
    difficulty: "Easy",
  },
  {
    id: 35,
    title: "Invert Binary Tree",
    completed: true,
    acceptance: 71.8,
    difficulty: "Easy",
  },
  {
    id: 36,
    title: "Merge k Sorted Lists",
    completed: true,
    acceptance: 47.5,
    difficulty: "Hard",
  },
  {
    id: 37,
    title: "String to Integer (atoi)",
    completed: true,
    acceptance: 79.4,
    difficulty: "Easy",
  },
  {
    id: 38,
    title: "Count and Say",
    completed: true,
    acceptance: 75.1,
    difficulty: "Easy",
  },
  {
    id: 39,
    title: "Permutations",
    completed: true,
    acceptance: 50.9,
    difficulty: "Medium",
  },
  {
    id: 40,
    title: "Rotate Image",
    completed: true,
    acceptance: 67.0,
    difficulty: "Medium",
  },
  {
    id: 41,
    title: "Three Sum",
    completed: true,
    acceptance: 44.1,
    difficulty: "Hard",
  },
  {
    id: 42,
    title: "Set Matrix Zeroes",
    completed: true,
    acceptance: 54.3,
    difficulty: "Medium",
  },
  {
    id: 43,
    title: "Remove Element",
    completed: true,
    acceptance: 77.6,
    difficulty: "Easy",
  },
  {
    id: 44,
    title: "Search in Rotated Sorted Array",
    completed: true,
    acceptance: 52.4,
    difficulty: "Medium",
  },
  {
    id: 45,
    title: "Maximal Square",
    completed: true,
    acceptance: 50.0,
    difficulty: "Medium",
  },
  {
    id: 46,
    title: "Zigzag Conversion",
    completed: true,
    acceptance: 62.0,
    difficulty: "Medium",
  },
  {
    id: 47,
    title: "Integer to Roman",
    completed: true,
    acceptance: 67.3,
    difficulty: "Medium",
  },
  {
    id: 48,
    title: "Substring with Concatenation of All Words",
    completed: true,
    acceptance: 43.2,
    difficulty: "Hard",
  },
  {
    id: 49,
    title: "Word Break",
    completed: true,
    acceptance: 71.4,
    difficulty: "Medium",
  },
  {
    id: 50,
    title: "Edit Distance",
    completed: true,
    acceptance: 46.3,
    difficulty: "Hard",
  },
];
